version: '3'

services:
  db:
    image: postgres
    container_name: storefront-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "sir{mahdi23}"
      POSTGRES_USER: "postgres"
      PGSERVICEFILE: ./.pg_service.conf
      POSTGRES_DB: storefront
    volumes:
      - /home/sirmahdi/Database/postgres/:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: storefront
    container_name: storefront-app
    environment:
      PGSERVICEFILE: ./.pg_service.conf
    ports:
      - "5000:5000"
    depends_on:
      - db

