version: '3'

services:
  postgres-db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "sir{mahdi23}"
      POSTGRES_USER: "postgres"
      PGSERVICEFILE: ./.pg_service.conf
    volumes:
      - /home/sirmahdi/Database/postgres/:/var/lib/postgresql/data

#  django-portal:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: app
#    restart: unless-stopped
#    ports:
#      - "5000:5000"